# 这里是home环境
server:
  port: 8080
logging:
  file: log/springboot-learning.log
  level:
    org.apache: WARN
    org.springframework: WARN
    com.felixfan.learn.filter: WARN
    com.felixfan.learn.controller: INFO
spring:
  application.name: springboot-learning
  output.ansi.enabled: always
  datasource:
    url: jdbc:mysql://192.168.0.201:3306/java?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.0.201
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  session:
    store-type: redis #默认使用的就是redis
  swagger:
    base-package: com.felixfan.learn
    enabled: true
  rabbitmq:
    username: admin
    password: 123456
    host: 192.168.0.201
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
mapper:
  mappers: tk.mybatis.mapper.common.Mapper,tk.mybatis.mapper.common.IdsMapper
  identity: MYSQL
mybatis:
  mapper-locations: classpath:com/felixfan/learn/mapper/*.xml
  type-aliases-package: com.felixfan.learn.entity.po
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  page-size-zero: true
  helper-dialect: mysql